### ISSUE TITLE
Support for macOS 12

### ISSUE THREAD

**Issue by adonboli** [mpanighetti/install-or-defer#73] opened 2022-02-03 15:04 UTC
Hello, 

Could you please modify the script so that it can run on macOS 12 as well? Unless there is a limitation that wouldn't allow this to run on macOS 12 that I do not know of? 

Thank you

**Comment by mpanighetti** [comment] 2022-02-03 18:30
Hey! Currently testing macOS Monterey support in my environment and will update the script once I've validated it works as expected. If you'd like to help test it, feel free to adjust the macOS version checks in a local copy of the script; [relevant bits are here](https://github.com/mpanighetti/install-or-defer/blob/main/payload/Library/Scripts/Install%20or%20Defer.sh#L420-L427). Let me know how that goes!

**Comment by mpanighetti** [comment] 2022-02-04 02:38
Closing as duplicate of #72, but macOS Monterey support is on track to be implemented in the next release.

**Closed by mpanighetti** 2022-02-04 02:38 UTC
Labels: duplicate
